fix(editor-server): Fix erlang install.

diff --git a/docker/editor-server/Dockerfile b/docker/editor-server/Dockerfile
--- a/docker/editor-server/Dockerfile
+++ b/docker/editor-server/Dockerfile
@@ -133,8 +133,8 @@ RUN apt-get install -y php-cli
 RUN curl -sSLf https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb -o /tmp/erlang-solutions_2.0_all.deb \
   && dpkg -i /tmp/erlang-solutions_2.0_all.deb \
   && apt-get update \
-  && apt-get install -y esl-erlang || apt-get install -y erlang \
-  && apt-get install -y elixir
+  && ( apt-get install -y esl-erlang \
+  && apt-get install -y elixir ) || echo "Install erlang has failed"
 
 # install ruby
 RUN apt-get install -y ruby-full
