fix: Update Dockerfile.alpine

diff --git a/docker/phoenix/Dockerfile.alpine b/docker/phoenix/Dockerfile.alpine
--- a/docker/phoenix/Dockerfile.alpine
+++ b/docker/phoenix/Dockerfile.alpine
@@ -13,6 +13,6 @@ RUN apk --force-broken-world --no-cache add make bash figlet git curl nodejs npm
 RUN mix local.rebar --force
 RUN mix local.hex --force
 RUN mix archive.install --force github hexpm/hex tag v2.0.6 || echo ">>>>>>>>>>>>>> failed"
-RUN mix archive.install --force hex phx_new ${PHOENIX_VERSION}
+RUN mix archive.install --force hex phx_new ${PHOENIX_VERSION} || echo ">>>>>>>>>>>>>>>> failed"
 
 ENTRYPOINT ["/bin/bash", "-c"]
